#
# Copyright 2021 Splunk Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: splunk-web
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 8000
      name: splunk-web
      protocol: TCP  
    hosts:
        - "*"
  - port:
      number: 8088
      name: splunk-hec
      protocol: TCP  
    hosts:
        - "*"
  - port:
      number: 8089
      name: https-splunk-mgmt
      protocol: TCP  
    hosts:
      - "*"
  - port:
      number: 9997
      name: tcp-splunk-s2s
      protocol: TCP
    hosts:
      - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: splunk-web
spec:
  hosts:
  - "*"
  gateways:
  - "splunk-web"
  tcp:
  - match:
    - port: 8000
    route:
    - destination:
        port:
          number: 8000
        host: splunk-s1-standalone-service
  - match:
    - port: 8088
    route:
    - destination:
        port:
          number: 8088
        host: splunk-s1-standalone-headless
  - match:
    - port: 8089
    route:
    - destination:
        port:
          number: 8089
        host: splunk-s1-standalone-headless
  - match:
    - port: 9997
    route:
    - destination:
        host: splunk-s1-standalone-service
        port: 
          number: 9997
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: splunk-s1-standalone-service
spec:
  host:  splunk-s1-standalone-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: SPLUNK_ISTIO_SESSION
          ttl: 3600s